// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwdVtK8P28baIFM5KmO68aMZYrvgfqLyA',
    appId: '1:323819117302:web:cd1ea15689bcf77d772ad7',
    messagingSenderId: '323819117302',
    projectId: 'airbnb-bfb7b',
    authDomain: 'airbnb-bfb7b.firebaseapp.com',
    storageBucket: 'airbnb-bfb7b.firebasestorage.app',
    measurementId: 'G-X3GRWF373P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADmcImVYyNVTyuLTQJXNOWuohMBfUAafA',
    appId: '1:323819117302:android:68f7b82b8086cf01772ad7',
    messagingSenderId: '323819117302',
    projectId: 'airbnb-bfb7b',
    storageBucket: 'airbnb-bfb7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArE4BuZLklbGTJNJWQqCFXtqp8A59NLJ4',
    appId: '1:323819117302:ios:c4e7f5be2c31f817772ad7',
    messagingSenderId: '323819117302',
    projectId: 'airbnb-bfb7b',
    storageBucket: 'airbnb-bfb7b.firebasestorage.app',
    iosBundleId: 'com.example.airbnb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArE4BuZLklbGTJNJWQqCFXtqp8A59NLJ4',
    appId: '1:323819117302:ios:c4e7f5be2c31f817772ad7',
    messagingSenderId: '323819117302',
    projectId: 'airbnb-bfb7b',
    storageBucket: 'airbnb-bfb7b.firebasestorage.app',
    iosBundleId: 'com.example.airbnb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwdVtK8P28baIFM5KmO68aMZYrvgfqLyA',
    appId: '1:323819117302:web:9ca05c6dfaa1ba0d772ad7',
    messagingSenderId: '323819117302',
    projectId: 'airbnb-bfb7b',
    authDomain: 'airbnb-bfb7b.firebaseapp.com',
    storageBucket: 'airbnb-bfb7b.firebasestorage.app',
    measurementId: 'G-026D3JMYM6',
  );
}
